Repository mrduckieduck/turbo-funicular, pull requests merged in 2020-11, with the labels that each got.

#19 Feature/bean validation
  gradle.properties
  src/main/java/turbo/funicular/config/FunicularConfig.java
  src/main/java/turbo/funicular/entity/User.java
  src/main/java/turbo/funicular/service/UsersMapper.java
  src/main/java/turbo/funicular/service/UsersService.java
  src/main/java/turbo/funicular/service/ValidationService.java
  src/main/java/turbo/funicular/web/UserCommand.java
  src/main/resources/i18n/messages.properties
  src/test/groovy/turbo/funicular/service/UsersServiceSpecs.groovy
Labels: model

#50 Adds timestamps to User domain class
  src/main/java/turbo/funicular/entity/User.java
  src/main/java/turbo/funicular/web/UserCommand.java
  src/main/resources/db/migration/V2__timestamps.sql
  src/test/groovy/turbo/funicular/entity/UserRepositorySpecs.groovy
Labels: db

#64 Pagina 404 y manejo de perfiles no existentes
  .gitignore
  src/main/java/turbo/funicular/web/UiController.java
  src/main/resources/i18n/messages.properties
  src/main/resources/static/css/style.css
  src/main/resources/views/404.html
  src/main/resources/views/profile.html
  src/main/resources/views/user_home.html
Labels: ui

#67 Feature/build and publish
  .circleci/config.yml
Labels: enhancement

#76 Agregar un comentario a gist
  src/main/java/turbo/funicular/security/UserDetailsMapper.java
  src/main/java/turbo/funicular/service/GithubApiClient.java
  src/main/java/turbo/funicular/web/GistComment.java
  src/main/java/turbo/funicular/web/UiController.java
  src/main/resources/views/gist_detail.html
  src/test/groovy/turbo/funicular/service/GithubApiClientSpecs.groovy
Labels: enhancement, ui
